### ISSUE TITLE
Reference not found

### ISSUE THREAD

**Issue by johnnyasantoss** [ziyasal/Autofac.Extras.NLog#11]
Hello!

I'm having a problem with your library. I have a ASPNET Core project using `net462`, and a test project using `net462` too. There is a method in my web project that injects `NLogModule` and if I call this method in a test I get an error.

`Message: System.IO.FileLoadException : Could not load file or assembly 'Autofac, Version=2.2.4.900, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

If I comment the line, rebuild and test again, the error goes away. 🤔

**Comment by evilroxx** [comment]
Seems like in correct version of Autofac. Did you fix this issue?

**Comment by CNBoland** [comment]
@johnnyasantoss @evilroxx Can you verify this is working for you with current versions of the [NuGet packages](https://www.nuget.org/packages/Autofac.Extras.NLog/3.0.1)?

**Comment by johnnyasantoss** [comment]
@CNBoland @evilroxx I no longer have access to the project where this error was occurring, so I can't test it.

I think that this issue could be closed since it's 2yrs old already.

**Comment by evilroxx** [comment]
@CNBoland I switched to Serilog and never looked back :D

**Comment by CNBoland** [comment]
@evilroxx @johnnyasantoss Thank you for the feedback.
