### ISSUE TITLE
callsite

### ISSUE THREAD

**Issue by ghoogland** [ziyasal/Autofac.Extras.NLog#14]
When you configure nlog to log the 'callsite', instead of the original calling function, you see Autofac.Extras.NLog.LoggerAdapter.Info.

**Example: in nlog config specify target with callsite variable:**
      <target name="file" type="File" fileName="${basedir}/logs/${shortdate}.log" layout="${longdate}  ${uppercase:${level}} ${callsite} ${message}" />

**in code:**
            _log.Info("Test");

**result:**
2017-05-31 09:11:16.2194 17 Autofac.Extras.NLog.LoggerAdapter.Info INFO Test

**Comment by davalillo** [comment]
Any solution for this issue?

**Comment by gerardhoogland-united** [comment]
I don't know. I did not encounter this problem anymore, because we worked around it. We did not use Autofac.Extras.NLog anymore.

**Comment by davalillo** [comment]
And how have you configured Nlog instead?

**Comment by gerardhoogland-united** [comment]
We created an own autofac-nlog class, defining and resolving the ILogger interface. Very small, and works as expected, but I am not sure which part of the code solves the 'callsite' problem. Unfortunately, I am not allowed to share this code.

**Comment by davalillo** [comment]
It's not a "live or death" situation. Thank you for your help.
