### ISSUE TITLE
Warning [NU1608] Detected package version outside of dependency constraint

### ISSUE THREAD

**Issue by andreikarkkanen** [ziyasal/Autofac.Extras.NLog#25]
A new version Autofac 7.0.1 has just been released

I would like mitigate the warning: Autofac.Extras.NLog 4.0.0 requires Autofac (>= 6.0.0 && < 7.0.0) but version Autofac 7.0.1 was resolved. Can you please extend range of supported versions.

`<PackageReference Include="Autofac" Version="[6.0.0, 7.0.0)" />`

**Comment by CNBoland** [comment]
Thank you for the notice. I've published [v4.0.1](https://www.nuget.org/packages/Autofac.Extras.NLog/4.0.1). Can you verify that works for you?

**Comment by andreikarkkanen** [comment]
The warning is gone. Thank you very much.
