### ISSUE TITLE
v1.2.2 causes code analysis error

### ISSUE THREAD

**Issue by ThreeScreenStudios** [ziyasal/Autofac.Extras.NLog#4]
Hi,

First off, thanks for making this library, it's been very valuable in integrating Autofac to my existing project with NLog. I upgraded to 1.2.2 via Nuget today, and have gotten the following error when building my solution:

CA0001	Error Running Code Analysis	CA0001 : Could not find type 'NLog.LoggerReconfiguredDelegate' in assembly 'Autofac.Extras.NLog, Version=1.2.2.0, Culture=neutral'.	[Errors and Warnings]	(Global)	

I was wondering if there was any troubleshooting you'd suggest to fix this, or should I just rollback to 1.2.1 for now? Thanks!

**Comment by janv8000** [comment]
I think this is related to #5 , LoggerReconfiguredDelegate was removed in NLog 2.0

**Comment by ziyasal** [comment]
I agree with @janv8000 #6 solves this issue

**Comment by ziyasal** [comment]
Pushed new version [1.2.3](https://www.nuget.org/packages/Autofac.Extras.NLog/)

**Comment by ThreeScreenStudios** [comment]
Sorry ziyasal, I totally dropped the ball on getting you a repro - glad janv8000 was able to help though! I just updated to 1.2.3 and it builds successfully - much appreciated.

**Comment by ziyasal** [comment]
@ThreeScreenStudios  Nope ;) All is well now.
