### ISSUE TITLE
Incompatible with NLog 2.0 api

### ISSUE THREAD

**Issue by janv8000** [ziyasal/Autofac.Extras.NLog#5]
NLog's API changed a bit with version 2.0, eg. the LoggerReconfiguredDelegate was replaced with the built-in EventHandler<EventArgs>.

But the nuget package declares its dependency for NLog without upper limit:
`<dependency id="NLog" version="1.0.0.505" />`

Doing a `Update-Package NLog` will pull-down the latest version (3.x), no longer containing the LoggerReconfiguredDelegate.

The NLog dependency should be changed as follows:
`<dependency id="NLog" version="(1.0.0.505,2.0]"  />`

**Comment by ziyasal** [comment]
Pushed new version [1.2.3](https://www.nuget.org/packages/Autofac.Extras.NLog/)
