### ISSUE TITLE
Could resolve ILogger when using service-locator pattern. (Not using ctor or property injetion)

### ISSUE THREAD

**Issue by polarbit** [ziyasal/Autofac.Extras.NLog#7]

**Comment by polarbit** [comment]
```csharp
public class TestClass
    {
        private readonly ILifetimeScope scope;

        public TestClass(ILifetimeScope scope)
        {
            this.scope = scope;
        }

        public void Publish<T>(T message) where T : IMessage
        {
            // Get logger from scope
            // Throws error!!!
            var logger = scope.Resolve<ILogger>();

            logger.Info("Publishing message : {0}", message);

            // ...
        }
    }
```

**Comment by ziyasal** [comment]
Thank you for your feedback @polarbit , NLogModule creates logger for dependent type and injects it. So, quick fix for your issue; to resolve ILogger when using service-locator you should register your ILogger  impl to container.

**Comment by sglogowski** [comment]
Hmmm... I have similar problem, so for service-locator pattern i should register separate binding? In this case should i still use this package or remove it? I guess that first answer is correct :D.

**Comment by ziyasal** [comment]
@sglogowski It'd be useful adding another Autofac module to resolve ILogger from service locator, anyway I'll take look asap. (:
